diccionario = {
    "Argentina": "Buenos Aires",
    "Australia": "Canberra",
    "Austria": "Viena",
    "Bélgica": "Bruselas",
    "Bolivia": "Sucre",
    "Brasil": "Brasilia",
    "Canadá": "Ottawa",
    "Chile": "Santiago",
    "China": "Pekín",
    "Colombia": "Bogotá",
    "Corea del Sur": "Seúl",
    "Costa Rica": "San José",
    "Cuba": "La Habana",
    "Dinamarca": "Copenhague",
    "Ecuador": "Quito",
    "Egipto": "El Cairo",
    "El Salvador": "San Salvador",
    "España": "Madrid",
    "Estados Unidos": "Washington D. C.",
    "Filipinas": "Manila",
    "Finlandia": "Helsinki",
    "Francia": "París",
    "Grecia": "Atenas",
    "Guatemala": "Ciudad de Guatemala",
    "Honduras": "Tegucigalpa",
    "Hungría": "Budapest",
    "India": "Nueva Delhi",
    "Indonesia": "Yakarta",
    "Irlanda": "Dublín",
    "Italia": "Roma",
    "Japón": "Tokio",
    "México": "Ciudad de México",
    "Nicaragua": "Managua",
    "Noruega": "Oslo",
    "Países Bajos": "Ámsterdam",
    "Panamá": "Ciudad de Panamá",
    "Paraguay": "Asunción",
    "Perú": "Lima",
    "Polonia": "Varsovia",
    "Portugal": "Lisboa",
    "Reino Unido": "Londres",
    "República Checa": "Praga",
    "República Dominicana": "Santo Domingo",
    "Rusia": "Moscú",
    "Suecia": "Estocolmo",
    "Suiza": "Berna",
    "Turquía": "Ankara",
    "Ucrania": "Kiev",
    "Uruguay": "Montevideo",
    "Venezuela": "Caracas"
}
invertido = {}
for pais, capital in diccionario.items():
    invertido[capital] = pais #Lo guardamos en otro diccionario con el orden invertido
for k, v in invertido.items():
    print(f"{k}: {v}") #Imprimimos el nuevo diccionario